batch_size: 16
epoch: 200
learning_rate: 1e-3
gpu: 1
num_point: 1024
optimizer: SGD
weight_decay: 1e-4
normal: False

defaults:
  - _self_
  - model: Hengshuang_new

hydra:
  run:
    dir: log/cls/${model.name}

  sweep:
    dir: log/cls
    subdir: ${model.name}
